name: Generate Critical CSS inline
on:
#  schedule:
#    - cron: "5 0 * * thu" # Every thursday at 00:05 UTC
  workflow_dispatch:

jobs:
  optimizecss:
    runs-on: ubuntu-latest
    steps:
      - name: Install critical
        run: |
          npm i -g critical
      - uses: actions/checkout@v4
      - name: Generate critical CSS
        run: | # Find all html files, remove inline style, get the directory location, generate based on the minified css in the same folder the critical CSS to the existing html
          find . -type f \( -iname "*.htm" -o -iname "*.html" \)|while read fname; do
            sed -i '/<style>.*<\/style>$/d' "$fname"
            dname=`dirname "$fname"`
            critical "$fname" --base . --inline --css "${dname}/*.min.css" > "$fname"-crit
            mv "$fname"-crit "$fname"
          done
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "purged & made critical CSS"
          git push
