name: Run Lighthouse CI
on:
  push:
    paths:
      - "**.webp"
      - "**.avif"
      - "**.html"
      - "**.css"
      - "**.js"
  pull_request:
    paths:
      - "**.webp"
      - "**.avif"
      - "**.html"
      - "**.css"
      - "**.js"
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - run: rm 404.html
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          #urls: |
          #  https://rockraidersx.com/
          budgetPath: '.github/.lighthouse/budget.json' # test performance budgets
          configPath: '.github/.lighthouse/lighthouserc.yml'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
