name: Change rockraiders.rocks 2 rockraiders.rocks
on:
  workflow_dispatch:

jobs:
  changer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Replace lrr with rocks website everywhere!
      run: |
          find ./ -type f -exec sed -i -e 's/rockraiders.rocks/rockraiders.rocks/g' {} \;
    - name: Commit files
      run: |
        git add .
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git diff --quiet && git diff --staged --quiet || git commit -am "Adjust to local fork"
        git push
