name: Refresh Mozzila HTTP Observatory Report
on:
  schedule:
    - cron: '0 0 * * mon' # Every monday at midnight
  workflow_dispatch:

jobs:
  refresh_score:
    runs-on: ubuntu-latest
    name: Refresh HTTP Observatory Report
    steps:
      - name: Curl the site to initiate refresh
        run: curl -L https://observatory.mozilla.org/analyze/lrr.researchrealm.net
