name: Optimize CSS
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *" # Every day at 00:00 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  optimizecss:
    runs-on: ubuntu-latest
    steps:
      # This fix "Missing write access to /usr/local/lib/node_modules" error
      - name: Setup node 14 properly
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install critical
        run: |
          npm i -g critical
      - name: Install purgecss
        run: |
          npm i -g purgecss
      - uses: actions/checkout@v4
      - name: Run purgecss
        run: |
          purgecss --css ../**/*.css --content "**.html" "**.js" --output assets/css/
      - name: Run critical
        run: | # Find each HTML file on root. remove online (critical)css. Add critical css to temp html file. Rename temp html file to original.
          find . -type f \( -iname "*.htm" -o -iname "*.html" \)|while read fname; do
            sed -i '/<style>.*<\/style>$/d' "$fname"
            critical "$fname" --base . --inline --css assets/css/*.css > "$fname"-crit
            mv "$fname"-crit "$fname"
          done
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "purged & made critical CSS"
          git push
  lighthouse:
    needs: optimizecss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm 404.html
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          budgetPath: '.github/.lighthouse/budget.json' # test performance budgets
          configPath: '.github/.lighthouse/lighthouserc.json'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
