name: Generate AVIF and WEBP
on:
  # Triggers the workflow on push or pull request events but only for the main branch and only when there's JPEG/PNG in the commmit!
  push:
    paths:
      - "**.jpe?g"
      - "**.png"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Convert-Compress:
    runs-on: ubuntu-latest
    steps:
      # This fixes the "Missing write access to /usr/local/lib/node_modules" error
      - name: Setup node 14 properly
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm i -g @funboxteam/optimizt
      - uses: actions/checkout@v4
      - name: run optimizt
        run: optimizt --verbose --force --avif --webp .
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "Create WebP & AVIF versions"
          git push
