name: Optimize CSS
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *" # Every day at 00:00 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  optimizecss:
    runs-on: ubuntu-latest
    steps:
      # This fix "Missing write access to /usr/local/lib/node_modules" error
      - name: Setup node 21 properly
        uses: actions/setup-node@v2
        with:
          node-version: 21
      - name: Install critical
        run: |
          npm i -g critical
      - uses: actions/checkout@v4
      - name: Run critical
        run: | # Find each HTML file on root. remove online (critical)css. Add critical css to temp html file. Rename temp html file to original.
          find . -type f \( -iname "*.htm" -o -iname "*.html" \)|while read fname; do
            sed -i '/<style>.*<\/style>$/d' "$fname"
            dname=`dirname "$fname"`
            critical "$fname" --base . --inline --css "${dname}/*.min.css" > "$fname"-crit
            mv "$fname"-crit "$fname"
          done
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "purged & made critical CSS"
          git push
