name: Full OWASP web security scan
on:
  schedule:
    - cron: '0 0 * * wed' # Every wednesday at 00:05 UTC
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan our website
    steps:
      - name: Get the ignore issues list
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://rockraiders.rocks/'
#          rules_file_name: '.github/.zap/rules.tsv'
