name: Refresh README.md Pagespeed
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "5 0 * * *" # Every day at 00:05 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  getpsresults:
    env:
      PSURL: https://pagespeed-insights-svg.glitch.me
      HOST: https://rockraiders.rocks
      RESULTSFOLDER: .github/.lighthouse/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create local changes
      run: | # Have to be sure a folder is present if not, make it
          mkdir -p ${RESULTSFOLDER}
          curl "${PSURL}/?url=${HOST}" > ./${RESULTSFOLDER}/PSIR.svg
    - name: Commit files
      run: |
        git add .
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git diff --quiet && git diff --staged --quiet || git commit -am "Updated Pagespeed results"
        git push
