name: Purge CSS
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  purgecss:
    runs-on: ubuntu-latest
    steps:
      # This fix "Missing write access to /usr/local/lib/node_modules" error
      - name: Setup node 14 properly
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install purgecss
        run: |
          npm i -g purgecss
      - uses: actions/checkout@v2 # This is a premade github action
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Run purgecss
        run: |
          find . -type f \( -iname "*.css" \) -not -name "*.min.css" | while read ffname; do
            dname=`dirname "$ffname"`
            fname=`basename "$ffname" .css`
            purgecss -css "$ffname" -con "**.html" "**.js" "**.php" -o "$dname""$fname".min.css
          done
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "purged CSS"
      - name: Push changes
        uses: ad-m/github-push-action@master # This is a premade github action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
