name: Purge CSS
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  purgecss:
    runs-on: ubuntu-latest
    steps:
      # This fix "Missing write access to /usr/local/lib/node_modules" error
      - name: Setup node 21 properly
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install purgecss
        run: |
          npm i -g purgecss
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Run purgecss
        run: | # Find's all css files with their full paths, we extract the full path minus the file, and then the filename withoud the extension and based on all html, js and php we write to the original location with .min between the filename and extension
          find . -type f \( -iname "*.css" \) -not -name "*.min.css" | while read cssfile; do
            dname=`dirname "$cssfile"`
            fname=`basename "$cssfile" .css`
            purgecss -css "$cssfile" -con "**.html" "**.js" "**.php" -o "$dname"/"$fname".min.css
          done
      - name: Commit files
        run: |
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet && git diff --staged --quiet || git commit -am "Updated minified CSS files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
